// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnmzwqb-8WY5r7e9aZzAA7UP8IwkzT258',
    appId: '1:753367395440:web:2d752861f937797e2b18b5',
    messagingSenderId: '753367395440',
    projectId: 'actividadcontacto-fa63d',
    authDomain: 'actividadcontacto-fa63d.firebaseapp.com',
    databaseURL: 'https://actividadcontacto-fa63d-default-rtdb.firebaseio.com',
    storageBucket: 'actividadcontacto-fa63d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMenuEXtkv2ugAr1hJTYifePz_0LJkXsU',
    appId: '1:753367395440:android:29a614c3f6eac1e62b18b5',
    messagingSenderId: '753367395440',
    projectId: 'actividadcontacto-fa63d',
    databaseURL: 'https://actividadcontacto-fa63d-default-rtdb.firebaseio.com',
    storageBucket: 'actividadcontacto-fa63d.firebasestorage.app',
  );

}